# The Docker image that will be used to build your app
image: node:16.14.2
# Functions that should be executed before the build script is run
variables:
    PUBLIC_URL: "/appleweekly" # slash is important
before_script:
  - rm -rf build
  - CI=false npm install
pages:
  script:
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
